"""
app.py
------
Chiller Plant Polynomial Regression — Research Prototype Dashboard

This is an interactive research-validation prototype for the forecasting
question: "Can Polynomial Regression reliably forecast chilled-water
return temperature (CHR) 15 minutes ahead using historical chiller-plant/
BMS measurements?"

No live BMS/SCADA connection exists. Every value shown comes from the
real historical dataset. Sections are labeled precisely: "Interactive
Prediction" (a simulator, not live), "Historical Forecast Replay" (a
replay of real historical test data), never "real-time" or "live BMS".

The model is described technically as Polynomial Regression throughout —
not as "AI" — per the scientific-honesty requirements of this build.

All charts reuse the exact PNGs generated by train.py, so the dashboard
and the saved experiment results are guaranteed to come from the same
reproducible pipeline.

Run:
    streamlit run app.py
"""

import json
import os
import time

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import streamlit as st

from train import (
    CHR_MODEL_PATH,
    EXPERIMENT_RESULTS_PATH,
    LOAD_MODEL_PATH,
    LOAD_TARGET_COL,
    METRICS_PATH,
    RESEARCH_DEGREES,
    TARGET_COL,
    TIMESTAMP_COL,
    clean_data,
    create_future_target,
    dev_test_split,
    engineer_features,
    find_dataset,
    load_data,
    plant_intelligence_status,
)

# Deep-model artifact paths are declared literally rather than imported from
# deep_models.py on purpose: that module imports torch, and pulling torch into
# the Streamlit process would add seconds to every page load and make the whole
# dashboard fail to start on a machine without it. The artifact itself is plain
# numpy/dict data, so it loads with joblib alone.
DEEP_ARTIFACT_PATH = "deep_artifact.pkl"
DEEP_METRICS_PATH = "metrics_deep.json"

# ---------------------------------------------------------------------------
# PAGE CONFIG + THEME
# ---------------------------------------------------------------------------
st.set_page_config(page_title="Chiller Plant Polynomial Regression — Research Prototype", layout="wide", initial_sidebar_state="expanded")

# --- Design tokens -----------------------------------------------------
# Monochrome / blueprint instrument-panel palette. Grounded in the
# subject: industrial SCADA panels are historically grayscale with a
# single reserved alarm color — that convention drives this theme rather
# than an arbitrary dark-mode palette. ALARM is reserved exclusively for
# the HIGH COOLING DEMAND state and hard errors; every other signal is
# conveyed by brightness/weight, never a second hue.
VOID = "#0a0a0b"
PANEL = "#131316"
CARD = "#17171a"
CARD_HOVER = "#1c1c20"
HAIR = "#26262b"
HAIR_BRIGHT = "#3a3a41"
INK = "#e6e6ea"
INK_DIM = "#8a8a92"
INK_FAINT = "#525259"
CHROME = "#c9c9d1"
ALARM = "#d9695c"

# legacy aliases used elsewhere in this file
BG, BORDER, TEXT, SUBTEXT, ACCENT = VOID, HAIR, INK, INK_DIM, CHROME
GREEN, AMBER, RED = INK_DIM, CHROME, ALARM

st.markdown(f"""
<style>
    @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@400;500;600&display=swap');

    .stApp {{ font-family: 'IBM Plex Sans', sans-serif; }}
    .stMarkdown, .stMarkdown p, .stMarkdown li, [data-testid="stCaptionContainer"] {{ font-family: 'IBM Plex Sans', sans-serif; }}

    /* Fixed blueprint grid backdrop: background-attachment:fixed means the
       grid stays put while content scrolls over it -- a reliable,
       JS-free way to get parallax-like depth that survives Streamlit's
       rerun-on-interaction model without any risk of breaking. */
    .stApp {{
        background-color: {VOID};
        color: {INK};
        background-image:
            linear-gradient(rgba(230,230,234,0.035) 1px, transparent 1px),
            linear-gradient(90deg, rgba(230,230,234,0.035) 1px, transparent 1px);
        background-size: 48px 48px;
        background-attachment: fixed;
    }}
    section[data-testid="stSidebar"] {{ background-color: {PANEL}; border-right: 1px solid {HAIR}; }}
    section[data-testid="stSidebar"] * {{ font-family: 'IBM Plex Mono', monospace; }}
    [data-testid="stIconMaterial"] {{ font-family: 'Material Symbols Rounded' !important; }}

    h1, h2, h3, h4, h5 {{
        color: {INK} !important; font-weight: 500 !important; letter-spacing: 0.2px;
        font-family: 'IBM Plex Mono', monospace;
    }}
    p, span, label, div {{ color: {INK}; }}
    .stCaption, [data-testid="stCaptionContainer"] {{ color: {INK_DIM} !important; font-family: 'IBM Plex Sans', sans-serif; }}

    /* Metric cards: hairline top-accent instead of a heavy full border,
       generous padding, near-square corners -- schematic, not soft SaaS. */
    div[data-testid="stMetric"] {{
        background-color: {CARD}; border: 1px solid {HAIR}; border-top: 2px solid {HAIR_BRIGHT};
        border-radius: 3px; padding: 14px 16px; transition: border-color 0.15s ease;
    }}
    div[data-testid="stMetric"]:hover {{ border-color: {HAIR_BRIGHT}; background-color: {CARD_HOVER}; }}
    div[data-testid="stMetricValue"] {{ font-family: 'IBM Plex Mono', monospace; }}

    /* Tabs styled as an instrument selector strip */
    .stTabs [data-baseweb="tab-list"] {{ gap: 2px; border-bottom: 1px solid {HAIR}; flex-wrap: wrap; }}
    .stTabs [data-baseweb="tab"] {{
        background-color: transparent; color: {INK_DIM}; border-radius: 2px 2px 0 0;
        font-family: 'IBM Plex Mono', monospace; font-size: 11.5px; letter-spacing: 0.8px;
        text-transform: uppercase; padding: 9px 14px; transition: color 0.15s ease;
    }}
    .stTabs [data-baseweb="tab"]:hover {{ color: {INK}; }}
    .stTabs [aria-selected="true"] {{ color: {INK} !important; border-bottom: 2px solid {CHROME}; }}

    div[data-testid="stExpander"] {{ background-color: {CARD}; border: 1px solid {HAIR}; border-radius: 3px; }}
    .stDataFrame {{ border: 1px solid {HAIR}; border-radius: 3px; }}
    .stDataFrame * {{ font-family: 'IBM Plex Mono', monospace !important; font-size: 12.5px; }}
    hr {{ border-color: {HAIR}; }}
    code {{ background-color: {CARD} !important; color: {CHROME} !important; border: 1px solid {HAIR}; font-family: 'IBM Plex Mono', monospace !important; }}
    .stAlert {{ background-color: {CARD}; border: 1px solid {HAIR}; }}
    .block-container {{ padding-top: 2rem; padding-bottom: 3rem; animation: fadeUp 0.5s ease-out; }}

    @keyframes fadeUp {{
        from {{ opacity: 0; transform: translateY(8px); }}
        to {{ opacity: 1; transform: translateY(0); }}
    }}

    .sys-header {{
        font-family: 'IBM Plex Mono', monospace; font-size: 11.5px; color: {INK_DIM};
        letter-spacing: 1px; padding: 8px 0 20px 0; border-bottom: 1px solid {HAIR}; margin-bottom: 28px;
    }}
    .sys-header b {{ color: {INK}; font-weight: 500; }}

    /* Section labels: technical eyebrow with a leading rule, generous
       vertical rhythm instead of sections sitting flush against each other */
    .section-label {{
        font-family: 'IBM Plex Mono', monospace; font-size: 11px; letter-spacing: 2.5px;
        color: {INK_DIM}; text-transform: uppercase; margin: 44px 0 16px 0; font-weight: 500;
        display: flex; align-items: center; gap: 10px;
    }}
    .section-label::before {{ content: ""; display: inline-block; width: 18px; height: 1px; background: {HAIR_BRIGHT}; }}

    .ind-card {{
        background-color: {CARD}; border: 1px solid {HAIR}; border-top: 2px solid {HAIR_BRIGHT};
        border-radius: 3px; padding: 16px 18px; margin-bottom: 10px; transition: all 0.15s ease;
    }}
    .ind-card:hover {{ border-color: {HAIR_BRIGHT}; transform: translateY(-1px); }}
    .ind-card .label {{ font-family: 'IBM Plex Mono', monospace; font-size: 10.5px; letter-spacing: 1.2px; color: {INK_DIM}; text-transform: uppercase; }}
    .ind-card .value {{ font-family: 'IBM Plex Mono', monospace; font-size: 27px; font-weight: 500; color: {INK}; margin-top: 4px; }}
    .ind-card .unit {{ font-size: 12px; color: {INK_DIM}; margin-left: 4px; }}

    .forecast-card {{
        background-color: {CARD}; border: 1px solid {HAIR}; border-top: 2px solid {HAIR_BRIGHT};
        border-radius: 4px; padding: 26px; transition: border-color 0.15s ease;
    }}
    .forecast-card:hover {{ border-color: {HAIR_BRIGHT}; }}
    .forecast-card .title {{ font-family: 'IBM Plex Mono', monospace; font-size: 11px; letter-spacing: 1.8px; color: {INK_DIM}; text-transform: uppercase; margin-bottom: 16px; }}
    .forecast-row {{ display: flex; align-items: baseline; gap: 16px; }}
    .forecast-current {{ font-family: 'IBM Plex Mono', monospace; font-size: 19px; color: {INK_DIM}; }}
    .forecast-future {{ font-family: 'IBM Plex Mono', monospace; font-size: 34px; font-weight: 500; color: {INK}; }}

    .chip {{
        display: inline-block; padding: 7px 14px; margin: 3px; border-radius: 2px; font-size: 12.5px;
        font-family: 'IBM Plex Mono', monospace; letter-spacing: 0.4px;
        border: 1px solid {HAIR}; background-color: {CARD};
    }}
    .dot {{ display: inline-block; width: 7px; height: 7px; border-radius: 50%; margin-right: 7px; }}
    .advisory-banner {{ border-radius: 4px; padding: 20px 24px; border: 1px solid {HAIR}; background-color: {CARD}; }}
    .note-box {{
        background-color: {CARD}; border-left: 2px solid {HAIR_BRIGHT}; border-radius: 2px;
        padding: 12px 16px; font-size: 12.5px; color: {INK_DIM}; margin: 10px 0;
        font-family: 'IBM Plex Mono', monospace;
    }}
</style>
""", unsafe_allow_html=True)

plt.rcParams.update({
    "figure.facecolor": PANEL, "axes.facecolor": PANEL, "savefig.facecolor": PANEL,
    "axes.edgecolor": HAIR, "axes.labelcolor": INK, "axes.grid": True,
    "grid.color": "#1e1e22", "grid.linewidth": 0.5,
    "xtick.color": INK_DIM, "ytick.color": INK_DIM, "text.color": INK,
    "legend.facecolor": CARD, "legend.edgecolor": HAIR, "legend.labelcolor": INK,
    "font.family": "monospace", "font.size": 10,
})
LINE_ACTUAL, LINE_PRED = INK, CHROME  # solid=actual, dashed=predicted — style distinguishes, not hue

# Brightness escalates with severity; ALARM (the one reserved hue) is used
# only for the genuinely critical state, matching real alarm-panel convention.
STATUS_COLORS = {"STABLE": INK_FAINT, "INCREASING DEMAND": INK_DIM, "EFFICIENCY WARNING": CHROME, "HIGH COOLING DEMAND": ALARM}


# ---------------------------------------------------------------------------
# HELPERS
# ---------------------------------------------------------------------------
@st.cache_resource
def try_load_artifact(path):
    if not os.path.exists(path):
        return None, "missing"
    try:
        return joblib.load(path), "ok"
    except Exception:
        return None, "corrupt"


@st.cache_data
def try_load_metrics():
    if not os.path.exists(METRICS_PATH):
        return None
    try:
        with open(METRICS_PATH) as f:
            return json.load(f)
    except Exception:
        return None


@st.cache_data
def try_load_and_prepare_data(_chr_features, _load_features):
    raw_df, _ = load_data()
    df = clean_data(raw_df, verbose=False)
    df = engineer_features(df)
    needed = list(set(_chr_features + _load_features + [TARGET_COL, LOAD_TARGET_COL]))
    df = df.dropna(subset=needed).reset_index(drop=True)
    return df


@st.cache_resource(show_spinner=False)
def _load_deep_artifact(mtime):
    """
    `mtime` is deliberately part of the cache key (no leading underscore, so
    Streamlit hashes it). Without it, a miss while deep_models.py is still
    running would cache None forever, and the Deep Learning / Explainable AI
    tabs would keep reporting "not found" even after training finished --
    looking like a failed run when the artifact is actually on disk.
    Passing the mtime (None when absent) invalidates the cache the moment the
    file appears or is regenerated.
    """
    if mtime is None:
        return None
    try:
        return joblib.load(DEEP_ARTIFACT_PATH)
    except Exception:
        return None


def try_load_deep_artifact():
    """Deep-model results are optional: the dashboard works without them."""
    mtime = os.path.getmtime(DEEP_ARTIFACT_PATH) if os.path.exists(DEEP_ARTIFACT_PATH) else None
    return _load_deep_artifact(mtime)


CHILLER_POWER_COLS = {
    1: ("DPM-CH-1-CP-1-kW", "DPM-CH-1-CP-2-kW"), 2: ("DPM-CH-2-CP-1-kW", "DPM-CH-2-CP-2-kW"),
    3: ("DPM-CH-3-CP-1-kW", "DPM-CH-3-CP-2-kW"), 4: ("DPM_CH-4-CP-1-kW", "DPM-CH-4-CP-2-kW"),
    5: ("DPM-CH-5-CP-1-kW", "DPM-CH-5-CP-2-kW"),
}
CHILLER_RUNNING_THRESHOLD_KW = 5.0
RESEARCH_VIZ_FEATURE = "CHR_lag1"  # most physically dominant single predictor — see Polynomial Regression tab


def get_chiller_statuses(row):
    out = []
    for n, (c1, c2) in CHILLER_POWER_COLS.items():
        if c1 not in row.index or c2 not in row.index:
            continue
        power = float(row[c1]) + float(row[c2])
        out.append({"chiller": n, "power_kw": power, "running": power > CHILLER_RUNNING_THRESHOLD_KW})
    return out


def metric_card(label, value, unit="", col=None):
    html = f"""<div class="ind-card"><div class="label">{label}</div><div class="value">{value}<span class="unit">{unit}</span></div></div>"""
    (col if col is not None else st).markdown(html, unsafe_allow_html=True)


def show_plot(path, caption=None):
    if os.path.exists(path):
        st.image(path, width='stretch')
        if caption:
            st.caption(caption)
    else:
        st.info(f"Plot not found: {path}. Run `python train.py` to generate it.")


# ---------------------------------------------------------------------------
# AVAILABILITY CHECKS
# ---------------------------------------------------------------------------
dataset_missing = find_dataset() is None
chr_artifact, chr_status = try_load_artifact(CHR_MODEL_PATH)
load_artifact_obj, load_status = try_load_artifact(LOAD_MODEL_PATH)
models_ok = chr_status == "ok" and load_status == "ok"

st.markdown("# CHILLER PLANT POLYNOMIAL REGRESSION")
st.markdown("##### Research Prototype — 15-Minute CHR Forecasting")

sys_status = "ONLINE" if (not dataset_missing and models_ok) else "DEGRADED"
model_status_txt = "TRAINED" if models_ok else ("NOT TRAINED" if not dataset_missing else "UNAVAILABLE")
st.markdown(f"""<div class="sys-header">
SYSTEM STATUS: <b>{sys_status}</b> &nbsp;|&nbsp; DATA SOURCE: <b>Historical BMS/SCADA dataset — no live connection</b> &nbsp;|&nbsp;
MODEL: <b>Polynomial Regression</b> &nbsp;|&nbsp; MODEL STATUS: <b>{model_status_txt}</b></div>""", unsafe_allow_html=True)

if dataset_missing:
    st.error("**DATASET NOT FOUND**\n\nPlease place the dataset inside:\n\n`data/dataset.csv` or `data/dataset.xlsx`")
    st.stop()
if not models_ok:
    missing = []
    if chr_status != "ok":
        missing.append("CHR model (model.pkl)")
    if load_status != "ok":
        missing.append("Cooling Load model (load_model.pkl)")
    st.error("**MODEL NOT TRAINED**\n\nMissing or unreadable: " + ", ".join(missing) + "\n\nRun:\n\n`python train.py`")
    st.stop()

metrics_json = try_load_metrics()
df = try_load_and_prepare_data(chr_artifact["feature_cols"], load_artifact_obj["feature_cols"])
feature_cols = chr_artifact["feature_cols"]
horizon = chr_artifact["horizon_minutes"]
best_degree = chr_artifact["best_degree"]
degree_pipelines = chr_artifact["degree_pipelines"]
ref_stats = chr_artifact["feature_reference_stats"]

latest_row = df.iloc[-1]
_, test_df_full = dev_test_split(df)
test_df_full = test_df_full.reset_index(drop=True)

# ---------------------------------------------------------------------------
# SIDEBAR
# ---------------------------------------------------------------------------
with st.sidebar:
    st.markdown("### CHILLER PLANT AI")
    st.caption("Research Prototype")
    st.markdown("---")
    st.caption("MODEL")
    st.markdown(f"Polynomial Regression, **degree {best_degree}** (selected by 10-fold CV)")
    st.caption(f"Forecast horizon: {horizon} min ({chr_artifact['forecast_horizon_rows']} rows @ {chr_artifact['interval_minutes']:.0f}-min interval)")
    st.markdown("---")
    st.caption("This is a research validation prototype using historical data only. "
                "No live BMS/SCADA connection exists.")

# ---------------------------------------------------------------------------
# TABS
# ---------------------------------------------------------------------------
deep_artifact = try_load_deep_artifact()

tabs = st.tabs([
    "Overview", "Interactive Prediction", "Polynomial Regression", "Training & Testing",
    "Cross Validation", "Error Analysis", "Experiment Results", "Deep Learning",
    "Explainable AI", "Model Information", "Plant Performance",
])
(tab_overview, tab_predict, tab_poly, tab_traintest, tab_cv, tab_error, tab_exp,
 tab_deep, tab_xai, tab_info, tab_plant) = tabs

# ================================================================ OVERVIEW
with tab_overview:
    st.markdown('<div class="section-label">Research Question</div>', unsafe_allow_html=True)
    st.markdown("*Can Polynomial Regression reliably forecast chilled-water return temperature (CHR) "
                "15 minutes ahead using historical chiller-plant/BMS measurements?*")

    st.markdown('<div class="section-label">Current Plant State (Latest Historical Record)</div>', unsafe_allow_html=True)
    st.caption(f"As of {latest_row[TIMESTAMP_COL]} — historical data, not live")
    cols = st.columns(5)
    metric_card("CHR", f"{latest_row[TARGET_COL]:.2f}", " °C", cols[0])
    metric_card("CHWS", f"{latest_row[chr_artifact['supply_col']]:.2f}", " °C", cols[1])
    metric_card("Cooling Load (est.)", f"{latest_row[LOAD_TARGET_COL]:,.0f}", " RT", cols[2])
    metric_card("Plant Power", f"{latest_row['Total_Plant_Power_kW']:,.0f}", " kW", cols[3])
    metric_card("Running Chillers", f"{int(latest_row['Running_Chillers'])}", "", cols[4])

    current_chr = float(latest_row[TARGET_COL])
    X_latest = latest_row[feature_cols].to_frame().T
    predicted_chr = float(chr_artifact["pipeline"].predict(X_latest)[0])
    chr_change = predicted_chr - current_chr

    current_load = float(latest_row[LOAD_TARGET_COL])
    X_load = latest_row[load_artifact_obj["feature_cols"]].to_frame().T
    predicted_load = float(load_artifact_obj["pipeline"].predict(X_load)[0])
    load_change = predicted_load - current_load

    st.markdown('<div class="section-label">Polynomial Regression Forecast</div>', unsafe_allow_html=True)
    fc1, fc2 = st.columns(2)
    with fc1:
        st.markdown(f"""<div class="forecast-card"><div class="title">CHR Forecast (degree {best_degree})</div>
        <div class="forecast-row"><div class="forecast-current">{current_chr:.2f} °C</div><div>&rarr;</div>
        <div class="forecast-future">{predicted_chr:.2f} °C</div></div>
        <div style="color:{CHROME if chr_change>0 else INK_FAINT}; margin-top:8px; font-size:13px;">Change: {chr_change:+.2f} °C over {horizon} min</div></div>""", unsafe_allow_html=True)
    with fc2:
        st.markdown(f"""<div class="forecast-card"><div class="title">Cooling Load Forecast</div>
        <div class="forecast-row"><div class="forecast-current">{current_load:,.0f} RT</div><div>&rarr;</div>
        <div class="forecast-future">{predicted_load:,.0f} RT</div></div>
        <div style="color:{CHROME if load_change>0 else INK_FAINT}; margin-top:8px; font-size:13px;">Change: {load_change:+.0f} RT over {horizon} min</div></div>""", unsafe_allow_html=True)
    st.caption("Cooling load is ESTIMATED (flow x ΔT), not a calibrated meter reading. See Plant Performance tab.")

    intel = chr_artifact["plant_intelligence"]
    n_chillers_now = str(int(latest_row["Running_Chillers"]))
    bucket = intel["config_bucket_stats"].get(n_chillers_now)
    current_kwrt = latest_row["Plant_kW_per_RT"]
    status = plant_intelligence_status(
        chr_change, load_change, intel["load_rising_threshold_rt"], intel["load_high_threshold_rt"],
        current_kw_per_rt=current_kwrt if pd.notna(current_kwrt) else None,
        efficiency_mean=bucket["mean_kw_per_rt"] if bucket else None,
        efficiency_std=bucket["std_kw_per_rt"] if bucket else None,
    )
    st.markdown('<div class="section-label">Advisory Status</div>', unsafe_allow_html=True)
    color = STATUS_COLORS.get(status, SUBTEXT)
    st.markdown(f"""<div class="advisory-banner" style="border-left: 4px solid {color};">
    <span class="dot" style="background-color:{color};"></span>
    <span style="font-size:18px; font-weight:700;">{status}</span>
    <div style="color:{SUBTEXT}; margin-top:8px; font-size:11px;">Advisory classification only, not an MPC recommendation. No commands sent to any equipment.</div>
    </div>""", unsafe_allow_html=True)

    st.markdown('<div class="section-label">Pipeline</div>', unsafe_allow_html=True)
    st.code(
        "Real BMS/SCADA Data -> Data Preprocessing -> Polynomial Regression -> "
        "15-Minute CHR Forecast -> Validation -> Visualization -> Interactive Research Prototype",
        language=None,
    )
    st.caption("MPC optimization is a future research stage — not implemented in this prototype.")

# ========================================================= INTERACTIVE PREDICTION
with tab_predict:
    st.markdown('<div class="section-label">Interactive Prediction</div>', unsafe_allow_html=True)
    sub_mode = st.radio(
        "Mode", ["Prediction Simulator", "Historical Forecast Replay"], horizontal=True,
        help="Prediction Simulator: adjust inputs freely and see the live Polynomial Regression output. "
             "Historical Forecast Replay: step through real historical test observations chronologically. "
             "Neither is a live BMS feed.",
    )
    degree_choice = st.selectbox("Polynomial Degree", options=sorted(degree_pipelines.keys()),
                                  index=sorted(degree_pipelines.keys()).index(best_degree),
                                  format_func=lambda d: f"Degree {d}" + (" (selected by CV)" if d == best_degree else ""))
    active_pipeline = degree_pipelines[degree_choice]

    if sub_mode == "Prediction Simulator":
        st.markdown('<div class="note-box">Adjust any input below to see a new Polynomial Regression prediction. '
                     'Sliders default to the latest real historical observation. This is a simulator — hypothetical '
                     'input combinations have no corresponding "actual" value.</div>', unsafe_allow_html=True)
        ref_row = latest_row
        cols = st.columns(3)
        inputs = {}
        changed = False
        for i, feat in enumerate(feature_cols):
            stats = ref_stats[feat]
            default = float(ref_row[feat])
            with cols[i % 3]:
                if feat in ("Hour", "DayOfWeek", "IsWeekend", "Running_Chillers"):
                    val = st.slider(feat, int(stats["min"]), int(stats["max"]), int(round(default)), key=f"sim_{feat}")
                else:
                    val = st.slider(feat, float(stats["min"]), float(stats["max"]), float(default), key=f"sim_{feat}")
            inputs[feat] = val
            if abs(val - default) > 1e-9:
                changed = True

        X_sim = pd.DataFrame([inputs])[feature_cols]
        pred_sim = float(active_pipeline.predict(X_sim)[0])

        st.markdown('<div class="section-label">Prediction</div>', unsafe_allow_html=True)
        pcol1, pcol2, pcol3 = st.columns(3)
        metric_card("Predicted CHR", f"{pred_sim:.2f}", " °C", pcol1)
        if not changed:
            actual_future_ts = ref_row[TIMESTAMP_COL] + pd.Timedelta(minutes=horizon)
            lookup = df.set_index(TIMESTAMP_COL)[TARGET_COL]
            actual_future = lookup.get(actual_future_ts, None)
            if actual_future is not None:
                metric_card("Actual CHR (real)", f"{actual_future:.2f}", " °C", pcol2)
                metric_card("Prediction Error", f"{actual_future - pred_sim:+.3f}", " °C", pcol3)
            else:
                metric_card("Actual CHR", "N/A", "", pcol2)
        else:
            pcol2.markdown('<div class="ind-card"><div class="label">Actual CHR</div>'
                            '<div class="value" style="font-size:16px;">N/A — hypothetical<br>input combination</div></div>', unsafe_allow_html=True)

    else:  # Historical Forecast Replay
        st.markdown('<div class="note-box">HISTORICAL FORECAST REPLAY — steps through real, held-out test '
                     'observations chronologically. Not a live BMS feed.</div>', unsafe_allow_html=True)
        n_test = len(test_df_full)
        if "replay_idx" not in st.session_state:
            st.session_state.replay_idx = 0
        if "replay_playing" not in st.session_state:
            st.session_state.replay_playing = False

        rc1, rc2, rc3 = st.columns([2, 1, 1])
        with rc2:
            step = st.slider("Step (rows/tick)", 1, 30, 5)
        with rc3:
            playing = st.toggle("Play", value=st.session_state.replay_playing)
            st.session_state.replay_playing = playing
        idx = st.slider("Test observation index", 0, n_test - 1, st.session_state.replay_idx)
        if not playing:
            st.session_state.replay_idx = idx
        idx = min(st.session_state.replay_idx, n_test - 1)
        row = test_df_full.iloc[idx]

        X_row = row[feature_cols].to_frame().T
        pred_row = float(active_pipeline.predict(X_row)[0])
        future_ts = row[TIMESTAMP_COL] + pd.Timedelta(minutes=horizon)
        lookup = df.set_index(TIMESTAMP_COL)[TARGET_COL]
        actual_row = lookup.get(future_ts, None)

        st.info(f"Test observation {idx+1} of {n_test} · {row[TIMESTAMP_COL]}")
        icol1, icol2, icol3, icol4 = st.columns(4)
        metric_card("Timestamp", str(row[TIMESTAMP_COL])[:16], "", icol1)
        metric_card("Predicted CHR", f"{pred_row:.2f}", " °C", icol2)
        if actual_row is not None:
            metric_card("Actual CHR", f"{actual_row:.2f}", " °C", icol3)
            metric_card("Error", f"{actual_row - pred_row:+.3f}", " °C", icol4)

        with st.expander("Input conditions for this observation"):
            st.dataframe(row[feature_cols].to_frame("value").round(3), width='stretch')

        if "replay_trail" not in st.session_state:
            st.session_state.replay_trail = {"t": [], "actual": [], "pred": []}
        trail = st.session_state.replay_trail
        if len(trail["t"]) == 0 or trail["t"][-1] != row[TIMESTAMP_COL]:
            trail["t"].append(row[TIMESTAMP_COL])
            trail["actual"].append(actual_row if actual_row is not None else np.nan)
            trail["pred"].append(pred_row)
        for k in trail:
            trail[k] = trail[k][-200:]

        fig, ax = plt.subplots(figsize=(12, 4))
        ax.plot(trail["t"], trail["actual"], label="Actual CHR", color=LINE_ACTUAL, linewidth=1.3)
        ax.plot(trail["t"], trail["pred"], label="Predicted CHR", color=LINE_PRED, linewidth=1.3, linestyle="--")
        ax.set_ylabel("°C")
        ax.legend(frameon=False)
        fig.autofmt_xdate(rotation=20)
        fig.tight_layout()
        st.pyplot(fig)

        if playing:
            if idx >= n_test - 1:
                st.session_state.replay_playing = False
                st.warning("Reached the end of the test period.")
            else:
                time.sleep(0.6)
                st.session_state.replay_idx = idx + step
                st.rerun()

# ========================================================= POLYNOMIAL REGRESSION
with tab_poly:
    st.markdown('<div class="section-label">Polynomial Regression Visualization</div>', unsafe_allow_html=True)
    st.caption("This model is multivariate (17 input features). To visualize it in 2D, one feature is swept "
               "across its observed range while all OTHER features are held at their reference (median) value. "
               "The curve is the model's actual response, not a fabricated illustration.")

    viz_degree = st.selectbox("Polynomial Degree to Visualize", options=sorted(degree_pipelines.keys()),
                               index=sorted(degree_pipelines.keys()).index(best_degree),
                               format_func=lambda d: f"Degree {d}" + (" (selected by CV)" if d == best_degree else ""),
                               key="viz_degree_select")
    st.markdown(f"**Swept feature:** `{RESEARCH_VIZ_FEATURE}` (current/most recent CHR reading — the single most "
                f"physically dominant predictor of near-term future CHR)")

    stats = ref_stats[RESEARCH_VIZ_FEATURE]
    sweep = np.linspace(stats["min"], stats["max"], 200)
    ref_values = {f: ref_stats[f]["median"] for f in feature_cols}
    sweep_df = pd.DataFrame([{**ref_values, RESEARCH_VIZ_FEATURE: v} for v in sweep])[feature_cols]
    curve = degree_pipelines[viz_degree].predict(sweep_df)

    dev_sample = df[[RESEARCH_VIZ_FEATURE, TARGET_COL]].sample(min(4000, len(df)), random_state=42)
    fig, ax = plt.subplots(figsize=(10, 5.5))
    ax.scatter(dev_sample[RESEARCH_VIZ_FEATURE], dev_sample[TARGET_COL], s=4, alpha=0.12, color=LINE_ACTUAL, label="Observed data (context)")
    ax.plot(sweep, curve, color=LINE_PRED, linewidth=2.2, label=f"Degree {viz_degree} fitted response")
    ax.set_xlabel(f"{RESEARCH_VIZ_FEATURE} (°C)")
    ax.set_ylabel(f"Predicted CHR_future_{horizon}min (°C)")
    ax.set_title(f"Model Response Curve — degree {viz_degree} (other {len(feature_cols)-1} features held at reference median)")
    ax.legend(frameon=False)
    fig.tight_layout()
    st.pyplot(fig)
    st.caption(
        "If this fitted line's slope looks different from the raw scatter's trend, that is a genuine "
        "and expected effect of holding correlated features fixed (a classic multivariate-regression "
        "confounding artifact), not a plotting error — the swept feature is correlated with several of "
        "the features held at their median, so its isolated marginal effect can differ from its simple "
        "bivariate relationship with the target. This is consistent with the multicollinearity instability "
        "documented for degrees 2-3 (see Cross Validation tab)."
    )

    with st.expander("Reference values used for held-constant features"):
        ref_df = pd.DataFrame([{"feature": f, "reference (median)": ref_stats[f]["median"]} for f in feature_cols if f != RESEARCH_VIZ_FEATURE])
        st.dataframe(ref_df.round(3), hide_index=True, width='stretch')

    st.markdown('<div class="section-label">Degree Comparison (10-fold CV)</div>', unsafe_allow_html=True)
    st.caption("Degrees 4 and 5 are computationally intractable on this 17-feature set — see Model Information tab.")
    dcol1, dcol2 = st.columns(2)
    with dcol1:
        show_plot("plot_research_degree_comparison_rmse.png")
        show_plot("plot_research_degree_comparison_r2.png")
    with dcol2:
        show_plot("plot_research_degree_comparison_mae.png")
        show_plot("plot_research_degree_stability.png", "Fraction of the 10 CV folds where the model achieved R² > 0.5.")

# ========================================================= TRAINING & TESTING
with tab_traintest:
    st.markdown('<div class="section-label">Training Set (Development Data)</div>', unsafe_allow_html=True)
    tcol1, tcol2, tcol3 = st.columns(3)
    metric_card("Training R²", f"{chr_artifact['train_metrics']['R2']:.4f}", "", tcol1)
    metric_card("Training MAE", f"{chr_artifact['train_metrics']['MAE']:.4f}", " °C", tcol2)
    metric_card("Training RMSE", f"{chr_artifact['train_metrics']['RMSE']:.4f}", " °C", tcol3)
    st.caption(f"n = {chr_artifact['dev_size']} rows ({chr_artifact['dev_date_range'][0]} to {chr_artifact['dev_date_range'][1]})")
    pcol1, pcol2, pcol3 = st.columns(3)
    with pcol1:
        show_plot("plot_research_train_actual_vs_predicted.png")
    with pcol2:
        show_plot("plot_research_train_residuals.png")
    with pcol3:
        show_plot("plot_research_train_error_distribution.png")

    st.markdown('<div class="section-label">Final Test Set (Held Out, Never Used for Degree Selection)</div>', unsafe_allow_html=True)
    tcol1, tcol2, tcol3 = st.columns(3)
    metric_card("Test R²", f"{chr_artifact['metrics']['R2']:.4f}", "", tcol1)
    metric_card("Test MAE", f"{chr_artifact['metrics']['MAE']:.4f}", " °C", tcol2)
    metric_card("Test RMSE", f"{chr_artifact['metrics']['RMSE']:.4f}", " °C", tcol3)
    st.caption(f"n = {chr_artifact['test_size']} rows ({chr_artifact['test_date_range'][0]} to {chr_artifact['test_date_range'][1]})")
    show_plot("plot_research_test_over_time.png")
    pcol1, pcol2 = st.columns(2)
    with pcol1:
        show_plot("plot_research_test_actual_vs_predicted.png")
    with pcol2:
        show_plot("plot_research_test_error_distribution.png")

# ========================================================= CROSS VALIDATION
with tab_cv:
    st.markdown('<div class="section-label">10-Fold TimeSeriesSplit Cross-Validation</div>', unsafe_allow_html=True)
    st.markdown(f"""
`sklearn.model_selection.TimeSeriesSplit(n_splits={chr_artifact['cv_n_splits']})` is used instead of ordinary
shuffled K-Fold. This guarantees every validation fold is strictly **after** its training fold in time —
an expanding-window design where training data only ever precedes validation data, never the reverse.
CV runs entirely within the Development set ({chr_artifact['dev_size']} rows); the Final Test set is never touched here.
""")
    cv_res = chr_artifact["cv_results_by_degree"][best_degree]
    ccol1, ccol2, ccol3 = st.columns(3)
    metric_card("CV Mean R²", f"{cv_res['summary']['mean_R2']:.4f}", f" ± {cv_res['summary']['std_R2']:.4f}", ccol1)
    metric_card("CV Mean MAE", f"{cv_res['summary']['mean_MAE']:.4f}", f" ± {cv_res['summary']['std_MAE']:.4f} °C", ccol2)
    metric_card("CV Mean RMSE", f"{cv_res['summary']['mean_RMSE']:.4f}", f" ± {cv_res['summary']['std_RMSE']:.4f} °C", ccol3)
    st.caption(f"Selected degree {best_degree}: {cv_res['summary']['n_folds_ok']}/{cv_res['summary']['n_folds_total']} folds usable.")

    pcol1, pcol2, pcol3 = st.columns(3)
    with pcol1:
        show_plot("plot_research_cv_folds_rmse.png")
    with pcol2:
        show_plot("plot_research_cv_folds_r2.png")
    with pcol3:
        show_plot("plot_research_cv_folds_mae.png")

    st.markdown('<div class="section-label">Fold-by-Fold Detail</div>', unsafe_allow_html=True)
    degree_for_table = st.selectbox("Degree", options=sorted(degree_pipelines.keys()), index=sorted(degree_pipelines.keys()).index(best_degree), key="cv_table_degree")
    fold_rows = chr_artifact["cv_results_by_degree"][degree_for_table]["folds"]
    st.dataframe(pd.DataFrame(fold_rows).round(4), hide_index=True, width='stretch')

# ========================================================= ERROR ANALYSIS
with tab_error:
    st.markdown('<div class="section-label">Residual Analysis (Final Test Set)</div>', unsafe_allow_html=True)
    st.caption("Residual = Actual CHR − Predicted CHR. All values come from actual model predictions.")
    pcol1, pcol2 = st.columns(2)
    with pcol1:
        show_plot("plot_research_test_residuals_vs_predicted.png", "Checks for heteroscedasticity (whether error size depends on the predicted value).")
    with pcol2:
        show_plot("plot_research_test_residuals_over_time.png", "Checks whether errors cluster around specific time periods/events.")
    show_plot("plot_research_test_error_distribution.png")

    test_resid = chr_artifact["test_actual"] - chr_artifact["test_predicted"]
    ecol1, ecol2, ecol3, ecol4 = st.columns(4)
    metric_card("Mean Residual", f"{test_resid.mean():+.4f}", " °C", ecol1)
    metric_card("Std Residual", f"{test_resid.std():.4f}", " °C", ecol2)
    metric_card("Max |Residual|", f"{np.abs(test_resid).max():.3f}", " °C", ecol3)
    metric_card("95th Pct |Residual|", f"{np.percentile(np.abs(test_resid), 95):.3f}", " °C", ecol4)

# ========================================================= EXPERIMENT RESULTS
with tab_exp:
    st.markdown('<div class="section-label">Degree Comparison Table</div>', unsafe_allow_html=True)
    exp_df = pd.DataFrame(chr_artifact["degree_comparison_table"])
    st.dataframe(exp_df.round(4), hide_index=True, width='stretch')
    if os.path.exists(EXPERIMENT_RESULTS_PATH):
        with open(EXPERIMENT_RESULTS_PATH, "rb") as f:
            st.download_button("Download experiment_results.csv", f, file_name="experiment_results.csv")

    st.markdown('<div class="section-label">Model Performance Dashboard</div>', unsafe_allow_html=True)
    st.markdown(f"**Model:** Polynomial Regression &nbsp;&nbsp; **Selected Degree:** {best_degree} &nbsp;&nbsp; "
                f"**Training Samples:** {chr_artifact['dev_size']} &nbsp;&nbsp; **Validation Folds:** {chr_artifact['cv_n_splits']} "
                f"&nbsp;&nbsp; **Forecast Horizon:** {horizon} min")

    mcol1, mcol2, mcol3 = st.columns(3)
    with mcol1:
        st.markdown("**Training**")
        st.dataframe(pd.DataFrame([chr_artifact["train_metrics"]]).round(4), hide_index=True, width='stretch')
    with mcol2:
        st.markdown("**Final Test**")
        st.dataframe(pd.DataFrame([chr_artifact["metrics"]]).round(4), hide_index=True, width='stretch')
    with mcol3:
        st.markdown("**Persistence Baseline (Test)**")
        st.dataframe(pd.DataFrame([chr_artifact["baseline_metrics"]]).round(4), hide_index=True, width='stretch')

    st.markdown(f"**Polynomial Regression vs Baseline:** RMSE {chr_artifact['baseline_metrics']['RMSE']:.4f} → "
                f"{chr_artifact['metrics']['RMSE']:.4f} °C ({'improvement' if chr_artifact['improved_over_baseline'] else 'no improvement'}), "
                f"R² {chr_artifact['baseline_metrics']['R2']:.4f} → {chr_artifact['metrics']['R2']:.4f}.")
    st.caption("R² is a goodness-of-fit statistic, not an 'accuracy' or 'confidence' score.")

    with st.expander("Top model coefficients (degree " + str(best_degree) + ")"):
        st.caption("Linear-model terms on scaled features — not physical causal effects.")
        st.dataframe(pd.DataFrame(chr_artifact["top_terms"]), hide_index=True, width='stretch')

    if metrics_json and "chr_multi_horizon_results" in metrics_json:
        with st.expander("Multi-horizon extension (15/30/45/60 min, secondary analysis, fixed degree)"):
            hrows = [{"Horizon (min)": h, "Baseline RMSE": round(v["baseline"]["RMSE"], 4),
                      "PolyReg RMSE": round(v["polyreg"]["RMSE"], 4), "PolyReg R2": round(v["polyreg"]["R2"], 4)}
                     for h, v in metrics_json["chr_multi_horizon_results"].items()]
            st.dataframe(pd.DataFrame(hrows), hide_index=True, width='stretch')

# ========================================================= MODEL INFORMATION
with tab_info:
    st.markdown('<div class="section-label">Reproducibility Configuration</div>', unsafe_allow_html=True)
    config_df = pd.DataFrame([
        {"parameter": "Random state", "value": str(chr_artifact["random_state"])},
        {"parameter": "Detected sampling interval", "value": f"{chr_artifact['interval_minutes']:.2f} min"},
        {"parameter": "Forecast horizon", "value": f"{horizon} min ({chr_artifact['forecast_horizon_rows']} rows)"},
        {"parameter": "Development fraction", "value": f"{int(chr_artifact['dev_frac']*100)}%"},
        {"parameter": "CV method", "value": f"TimeSeriesSplit, {chr_artifact['cv_n_splits']} folds, expanding window"},
        {"parameter": "Degrees tested", "value": str(chr_artifact["research_degrees_tested"])},
        {"parameter": "Tractability ceiling", "value": f"{chr_artifact['max_tractable_poly_terms']} polynomial terms"},
        {"parameter": "Selected degree", "value": str(best_degree)},
        {"parameter": "Number of input features", "value": str(len(feature_cols))},
    ])
    st.dataframe(config_df, hide_index=True, width='stretch')

    st.markdown('<div class="section-label">Target Definition</div>', unsafe_allow_html=True)
    st.markdown(f"**CHR_future_{horizon}min** = value of `{TARGET_COL}` at timestamp *t + {horizon} min*, "
                f"looked up by actual elapsed time (not a fixed row offset), so the target remains correct even "
                f"if any rows were removed during cleaning.")

    st.markdown('<div class="section-label">Input Features</div>', unsafe_allow_html=True)
    st.dataframe(pd.DataFrame({"feature": feature_cols}), hide_index=True, width='stretch')

    st.markdown('<div class="section-label">Why Degrees 4 and 5 Are Not Available</div>', unsafe_allow_html=True)
    st.markdown(f"""
With {len(feature_cols)} input features, PolynomialFeatures produces:
degree 4 → 5,985 terms, degree 5 → 26,334 terms. Empirically in this environment, degree 4 took 16s to fit
on a ~3,450-row fold and was **OOM-killed** on a ~34,500-row fold. Degree 5 is worse. Both are reported as
**computationally intractable** on this feature set — not silently hidden. Degrees 1-3 were fully cross-validated.
""")

    st.markdown('<div class="section-label">Limitations</div>', unsafe_allow_html=True)
    st.markdown("""
- **Historical data only** — no live BMS/SCADA connection exists in this prototype.
- **Cooling load is an estimate** (physical flow × ΔT calculation), not a calibrated meter reading — flow-sensor
  unit tags in the source export are demonstrably unreliable elsewhere, so an L/s assumption was made and
  cross-checked against a plausible resulting kW/RT range.
- **Polynomial degree is capped at 3** for this feature count — higher degrees are numerically intractable, not
  just "not tried."
- **Degrees 2 and 3 are unstable across CV folds** (see Cross Validation tab) — likely driven by multicollinearity
  among the four CHR lag features once cross-multiplied; this is reported, not hidden, and is why degree 1
  (the simplest, most stable model) was correctly selected by the CV procedure.
- **A single chiller plant, one month of data** — generalization to other plants or seasons is untested.
- **No per-chiller cooling-load metering** exists, so chiller-level efficiency cannot be computed.
- **The chiller-configuration comparison (Plant Performance tab) is descriptive historical analysis**, not an
  optimization recommendation.
""")

    st.markdown('<div class="section-label">Research Next Step</div>', unsafe_allow_html=True)
    st.markdown("""
With a validated, leakage-safe, cross-validated 15-minute CHR forecasting layer in place (and Cooling Load
forecasting alongside it), the logical next stage — **not implemented in this prototype** — is a Model
Predictive Control (MPC) layer that takes these forecasts as inputs, models chiller/pump/cooling-tower
efficiency curves, and searches over feasible setpoints to minimize energy while respecting comfort and
equipment constraints. Given the instability observed at degree ≥ 2, a regularized approach (e.g. Ridge or
Lasso) or a reduced/selected feature set would likely be a necessary prerequisite before extending polynomial
degree further, rather than proceeding to MPC on an unstable forecasting layer.
""")

# ========================================================= PLANT PERFORMANCE
with tab_plant:
    row = latest_row
    st.markdown('<div class="section-label">Energy & Efficiency</div>', unsafe_allow_html=True)
    ecols = st.columns(5)
    metric_card("Total Chiller Power", f"{row['Total_Chiller_Power_kW']:,.0f}", " kW", ecols[0])
    metric_card("Total Pump Power", f"{row['Total_CHWP_Power_kW'] + row['Total_CWP_Power_kW']:,.0f}", " kW", ecols[1])
    metric_card("Cooling Tower Power", f"{row['Total_CT_Power_kW']:,.0f}", " kW", ecols[2])
    metric_card("Total Plant Power", f"{row['Total_Plant_Power_kW']:,.0f}", " kW", ecols[3])
    kwrt = row["Plant_kW_per_RT"]
    metric_card("Plant kW/RT", f"{kwrt:.3f}" if pd.notna(kwrt) else "N/A", "", ecols[4])
    st.caption("Chiller-level kW/RT is not shown: no per-chiller cooling-load metering exists in this dataset.")

    st.markdown('<div class="section-label">Chiller Status</div>', unsafe_allow_html=True)
    statuses = get_chiller_statuses(row)
    if statuses:
        chips = "".join(
            f'<span class="chip"><span class="dot" style="background-color:{CHROME if s["running"] else INK_FAINT};"></span>'
            f'CHILLER {s["chiller"]:02d} &nbsp; {"RUNNING" if s["running"] else "OFF"}</span>' for s in statuses
        )
        st.markdown(chips, unsafe_allow_html=True)
        st.caption(f"Inferred from per-chiller compressor power (threshold: >{CHILLER_RUNNING_THRESHOLD_KW:.0f} kW). Display only.")

    st.markdown('<div class="section-label">Historical Chiller-Configuration Comparison</div>', unsafe_allow_html=True)
    st.caption("Historical operating analysis only — not an optimization recommendation.")
    if metrics_json and metrics_json.get("chiller_config_analysis", {}).get("table"):
        cfg = metrics_json["chiller_config_analysis"]
        cfg_df = pd.DataFrame(cfg["table"]).rename(columns={
            "running_chillers": "Chillers Running", "n_samples": "Samples", "avg_cooling_load_rt": "Avg Load (RT)",
            "avg_plant_power_kw": "Avg Power (kW)", "avg_kw_per_rt": "Avg kW/RT", "std_kw_per_rt": "Std kW/RT",
        })
        st.dataframe(cfg_df.round(1), hide_index=True, width='stretch')
        if cfg.get("skipped_configs"):
            st.caption(f"Skipped {cfg['skipped_configs']}: {cfg['skip_reason']}")

    st.markdown('<div class="section-label">Cooling Load Model Performance</div>', unsafe_allow_html=True)
    lcol1, lcol2, lcol3 = st.columns(3)
    metric_card("R²", f"{load_artifact_obj['metrics']['R2']:.4f}", "", lcol1)
    metric_card("RMSE", f"{load_artifact_obj['metrics']['RMSE']:.2f}", " RT", lcol2)
    metric_card("MAE", f"{load_artifact_obj['metrics']['MAE']:.2f}", " RT", lcol3)
    with st.expander("Cooling Load Methodology"):
        if metrics_json:
            m = metrics_json["cooling_load_methodology"]
            st.markdown(f"**Formula:** `{m['formula']}`")
            st.markdown(f"**Risers summed:** {', '.join(m['risers_used'])}")
            st.markdown(f"**Unit assumption:** {m['unit_assumption']}")
            st.markdown(f"**Sanity check:** mean implied plant kW/RT = {m['sanity_check_kw_per_rt_mean']:.3f} "
                         "(plausible for a real chiller plant — still an ESTIMATE, not a calibrated reading).")

# ========================================================= DEEP LEARNING
with tab_deep:
    st.markdown('<div class="section-label">Deep Sequence Models</div>', unsafe_allow_html=True)
    if deep_artifact is None:
        st.info("Deep-model results not found. Run `python deep_models.py` to train the six "
                "architectures and generate this section.")
    else:
        da = deep_artifact
        st.markdown(f"""
Six deep architectures were trained on the **same forecasting question** as the polynomial model —
CHR {da['horizon_minutes']} minutes ahead — but from a different input form: a sliding
**{da['seq_len']}-timestep ({da['seq_len'] * da['interval_minutes']:.0f}-minute) lookback window**
over {len(da['seq_feature_cols'])} sensor channels, rather than a flat row of hand-built lag features.

Every model below is scored on the **identical** set of {da['split']['test']:,} Final-Test windows
({da['test_date_range'][0]} to {da['test_date_range'][1]}), against the identical persistence baseline.
""")

        # ---- leaderboard ----
        st.markdown('<div class="section-label">Final Test Leaderboard</div>', unsafe_allow_html=True)
        lb = []
        for name in da["ranking"]:
            m = da["model_metrics"][name]
            tr = da["model_training"][name]
            lb.append({
                "Model": name, "Family": "Deep", "MAE (°C)": m["MAE"], "RMSE (°C)": m["RMSE"],
                "R²": m["R2"], "Δ RMSE vs persistence": m["RMSE"] - da["baseline_metrics"]["RMSE"],
                "Params": tr["n_params"], "Epochs": tr["epochs_run"], "Train (s)": tr["train_seconds"],
            })
        lb.append({"Model": "Persistence", "Family": "Baseline", "MAE (°C)": da["baseline_metrics"]["MAE"],
                   "RMSE (°C)": da["baseline_metrics"]["RMSE"], "R²": da["baseline_metrics"]["R2"],
                   "Δ RMSE vs persistence": 0.0, "Params": 0, "Epochs": 0, "Train (s)": 0.0})
        if da.get("poly_metrics"):
            lb.append({"Model": "PolyReg degree 1", "Family": "Classical",
                       "MAE (°C)": da["poly_metrics"]["MAE"], "RMSE (°C)": da["poly_metrics"]["RMSE"],
                       "R²": da["poly_metrics"]["R2"],
                       "Δ RMSE vs persistence": da["poly_metrics"]["RMSE"] - da["baseline_metrics"]["RMSE"],
                       "Params": 18, "Epochs": 0, "Train (s)": 0.0})
        st.dataframe(pd.DataFrame(lb).round(4), hide_index=True, width='stretch')
        st.caption("Sorted by Final Test RMSE (deep models first). Negative Δ = better than persistence. "
                   "Params/Epochs are reported so the accuracy-vs-cost trade-off is visible, not hidden.")

        best = da["best_model"]
        bm = da["model_metrics"][best]
        st.markdown(f'<div class="section-label">Best Deep Model — {best}</div>', unsafe_allow_html=True)
        bcols = st.columns(4)
        metric_card("R²", f"{bm['R2']:.4f}", "", bcols[0])
        metric_card("RMSE", f"{bm['RMSE']:.4f}", " °C", bcols[1])
        metric_card("MAE", f"{bm['MAE']:.4f}", " °C", bcols[2])
        metric_card("Parameters", f"{da['model_training'][best]['n_params']:,}", "", bcols[3])

        # ---- honest verdict against the simpler models ----
        beat_base = [n for n in da["ranking"]
                     if da["model_metrics"][n]["RMSE"] < da["baseline_metrics"]["RMSE"]]
        if da.get("poly_metrics"):
            beat_poly = [n for n in da["ranking"]
                         if da["model_metrics"][n]["RMSE"] < da["poly_metrics"]["RMSE"]]
            if beat_poly:
                st.success("**Deep models that beat Polynomial Regression (degree 1) on Final Test RMSE:** "
                           + ", ".join(beat_poly))
            else:
                st.warning("**No deep model beat Polynomial Regression (degree 1) on Final Test RMSE.** "
                           "That is a legitimate result, not a failure to report: on this dataset the "
                           "15-minute CHR signal is dominated by short-range persistence, which a linear "
                           "model already captures. It is reported here rather than buried.")
        st.caption("Deep models beating the persistence baseline: "
                   + (", ".join(beat_base) if beat_base else "none") + ".")

        st.markdown('<div class="section-label">Model Comparison</div>', unsafe_allow_html=True)
        ccol1, ccol2, ccol3 = st.columns(3)
        with ccol1:
            show_plot("plot_deep_comparison_rmse.png")
        with ccol2:
            show_plot("plot_deep_comparison_mae.png")
        with ccol3:
            show_plot("plot_deep_comparison_r2.png")

        st.markdown('<div class="section-label">Training Behaviour</div>', unsafe_allow_html=True)
        show_plot("plot_deep_training_curves.png",
                  "Validation RMSE per epoch. The red dot marks the early-stopping checkpoint actually "
                  "restored and used for testing — not the final epoch.")

        st.markdown('<div class="section-label">Forecast Replay — Best Deep Model</div>', unsafe_allow_html=True)
        show_plot("plot_deep_test_over_time.png",
                  "Historical replay of real Final-Test data. Not a live BMS feed.")
        dcol1, dcol2 = st.columns(2)
        with dcol1:
            show_plot("plot_deep_test_scatter.png")
        with dcol2:
            show_plot("plot_deep_test_residuals.png")
        show_plot("plot_deep_test_error_distribution.png")

        st.markdown('<div class="section-label">Architectures</div>', unsafe_allow_html=True)
        arch_rows = [{"Model": n, "Description": d, "Parameters": da["model_training"][n]["n_params"],
                      "Best epoch": da["model_training"][n]["best_epoch"],
                      "Val RMSE (°C)": round(da["model_training"][n]["best_val_RMSE"], 4)}
                     for n, d in da["model_descriptions"].items()]
        st.dataframe(pd.DataFrame(arch_rows), hide_index=True, width='stretch')

        with st.expander("Training configuration & methodology"):
            hp = da["hyperparameters"]
            channels = ", ".join("`" + c + "`" for c in da["seq_feature_cols"])
            st.markdown(f"""
**Optimizer** `{hp['optimizer']}` · **Loss** `{hp['loss']}` · **LR** `{hp['learning_rate']}` ·
**Weight decay** `{hp['weight_decay']}` · **Batch** `{hp['batch_size']}` ·
**Hidden size** `{hp['hidden_size']}` · **CNN channels** `{hp['cnn_channels']}` ·
**Dropout** `{hp['dropout']}` · **Grad clip** `{hp['grad_clip']}` ·
**Max epochs** `{hp['max_epochs']}` · **Early-stopping patience** `{hp['patience']}` ·
**Seed** `{hp['random_state']}`

**Split (chronological, never shuffled)** — Train {da['split']['train']:,} ·
Validation {da['split']['val']:,} · Final Test {da['split']['test']:,}
(dev fraction {da['split']['dev_frac']}, matching the polynomial CHR pipeline).

**Leakage controls**

- Feature scalers are fit on the **training rows only**, then applied to validation and test.
- Early stopping selects on the **validation** slice; the Final Test set is evaluated exactly once.
- Lookback windows that would span a gap in the timestamp index are **dropped**, not stitched.
- The target at *t + {da['horizon_minutes']} min* is fetched by timestamp, never by row offset alone.

**Input channels ({len(da['seq_feature_cols'])})**: {channels}
""")

# ========================================================= EXPLAINABLE AI
with tab_xai:
    st.markdown('<div class="section-label">Explainable AI</div>', unsafe_allow_html=True)
    if deep_artifact is None or not deep_artifact.get("xai"):
        st.info("Explainability results not found. Run `python deep_models.py` to generate this section.")
    else:
        da = deep_artifact
        xai = da["xai"]
        st.markdown("""
A deep sequence model is not self-explanatory, so three complementary methods are applied.
They answer different questions and are **not** interchangeable — each is labelled with what it
actually measures.

| Method | Question it answers | Model-agnostic? |
|---|---|---|
| **Permutation Importance** | Which sensor channel does the model actually *rely on*? | Yes — comparable across all architectures |
| **Integrated Gradients** | How much did each input value *contribute* to the prediction? | No — needs gradients |
| **Attention / Temporal saliency** | Which *minutes* of the lookback window mattered? | No — attention-based where available |
""")

        model_names = list(xai.keys())
        default_idx = model_names.index(da["best_model"]) if da["best_model"] in model_names else 0
        sel = st.selectbox("Model to explain", options=model_names, index=default_idx, key="xai_model")
        x = xai[sel]

        # ---- permutation importance ----
        st.markdown('<div class="section-label">1 · Permutation Importance</div>', unsafe_allow_html=True)
        st.caption(f"Each channel is shuffled across test windows (its internal time structure preserved, "
                   f"its link to the target destroyed) and the increase in Final-Test RMSE is measured. "
                   f"Unpermuted reference RMSE for {sel}: {x['permutation']['baseline_rmse']:.4f} °C.")
        pcol1, pcol2 = st.columns([3, 2])
        with pcol1:
            show_plot(f"plot_xai_permutation_{sel.lower()}.png")
        with pcol2:
            perm_df = pd.DataFrame(x["permutation"]["importances"]).rename(columns={
                "feature": "Channel", "importance_rmse_increase": "RMSE increase (°C)", "std": "Std"})
            st.dataframe(perm_df.round(5), hide_index=True, width='stretch')
        top = x["permutation"]["importances"][0]
        st.caption(f"Most relied-upon channel for {sel}: **{top['feature']}** "
                   f"(+{top['importance_rmse_increase']:.4f} °C RMSE when destroyed). "
                   "A near-zero or negative value means the model effectively ignores that channel.")

        # ---- integrated gradients ----
        st.markdown('<div class="section-label">2 · Integrated Gradients</div>', unsafe_allow_html=True)
        st.caption("Sundararajan et al. (2017). Attribution is integrated along a straight path from a "
                   "baseline window — the all-zeros window, which in standardised space is the training "
                   "mean, i.e. 'a completely average half-hour of plant operation' — to the real input.")
        gcol1, gcol2 = st.columns([3, 2])
        with gcol1:
            show_plot(f"plot_xai_integrated_gradients_{sel.lower()}.png")
        with gcol2:
            ig = x["integrated_gradients"]
            ig_df = pd.DataFrame({"Channel": ig["feature_names"],
                                  "Mean |attribution|": ig["per_feature"]}).sort_values(
                "Mean |attribution|", ascending=False)
            st.dataframe(ig_df.round(5), hide_index=True, width='stretch')

        # ---- temporal ----
        st.markdown('<div class="section-label">3 · Temporal Attention / Saliency</div>', unsafe_allow_html=True)
        st.caption(f"Source for {sel}: **{x['temporal']['source']}** — {x['temporal']['note']}")
        show_plot("plot_xai_temporal_profiles.png",
                  "Solid lines are learned attention weights; dashed lines are normalised |Integrated "
                  "Gradients| for architectures with no attention head. The two are plotted together for "
                  "comparison but are not the same quantity.")
        weights = np.array(x["temporal"]["weights"])
        lag_axis = np.arange(-(len(weights) - 1), 1)
        peak = int(np.argmax(weights))
        tcol1, tcol2, tcol3 = st.columns(3)
        metric_card("Peak-weight timestep", f"t{lag_axis[peak]:+d}", " min", tcol1)
        metric_card("Weight on most recent 5 min", f"{weights[-5:].sum() * 100:.1f}", " %", tcol2)
        metric_card("Uniform reference", f"{100.0 / len(weights):.1f}", " % per step", tcol3)
        st.caption("If a model concentrates its weight on the most recent few minutes, it is behaving "
                   "much like the persistence baseline — which is itself a finding worth reporting.")

        # ---- cross-model agreement ----
        st.markdown('<div class="section-label">Cross-Architecture Agreement</div>', unsafe_allow_html=True)
        st.caption("Permutation importance is the one method directly comparable across architectures. "
                   "Where independent models agree on which channels matter, the finding is far more "
                   "credible than any single model's explanation.")
        show_plot("plot_xai_feature_agreement.png")

        agree = {}
        for name, xx in xai.items():
            for rank, item in enumerate(xx["permutation"]["importances"]):
                agree.setdefault(item["feature"], {})[name] = rank + 1
        agree_df = pd.DataFrame(agree).T
        agree_df["Mean rank"] = agree_df.mean(axis=1)
        agree_df = agree_df.sort_values("Mean rank")
        agree_df.index.name = "Channel"
        st.dataframe(agree_df.round(2), width='stretch')
        st.caption("Importance *rank* per architecture (1 = most important). Consistently low rows are "
                   "the channels every architecture independently found predictive.")
